kind: ENC[AES256_GCM,data:JNjBmOzj,iv:SQNqZT5fGzYQg8dt9elu9XligT2aL62SPqhW4Sb4XC8=,tag:jg2EFqH18B+mAMt05IXRhg==,type:str]
ansible_user: ENC[AES256_GCM,data:wepeBZq/CQ==,iv:wbf6IsnC2g5sD/Cy4UFch6XZbgujybfMAwvcXfsED1E=,tag:csgbXR2IYr+J+lc9GpsiIQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Td/pZQZPIj8fFLo=,iv:i7ytWzGrBAWCNbQSAvapokcVqmiZdhYbV3gGWg79THU=,tag:UbTnKne4ksbRY/37LR7lrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q0kewssezsdnnf42tkgw2nsjl5qqvvquteftg6cxnzj6cuflrujsumrq5p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdjRvMWRQWFBOcFZITGJj
            SnZya0ZuUlY2Q2d4VGdISE1FeGlSTWJXZ0g0CnpwMzlQQ3dpY2FMWUdjWWNsZGhy
            Y2syc2NScTZpZ2c1Mk9UV0hTT1VqK2MKLS0tIEF6Qm1TVUV1M29ocUpZQnN0SFN6
            WHRCS1FDSGJjWjgwcFFueUtqRm1QMzQKQSsGgfE6ZbEJ1UesxNz9mCutkDSBfqu8
            00N70aIQ2lQYTkYIURz7TOGeHJHXJPxiDVWcEaoBqIXDu4eq7b7PDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-05T03:08:12Z"
    mac: ENC[AES256_GCM,data:erNfXr9e3kkwAhcVV0DD6csiivSAsyUUwKPca7YtQvoUf8MtpgG+8nM8vdJhyyH8rw18O51aAbuRky3Igbk7Dxq9DUOH72u35cMBbS2S9KgcXlNnhn/DgDai5Y2DuBXa2Lzx/D4zSl1t1tgPbo8PIdhAh+HwzVQym/ey3iol9t8=,iv:ntKym4lyuocxv5JpJmYfBFD21xrLbyZbbIiMmfGGTb0=,tag:2tPwdyZo+jMwv/D9a9rDCQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
