kind: ENC[AES256_GCM,data:i6ktMZoH,iv:ygOJsmv3WGMaZf47uAohDQbLPGxccvgv+k/+4YepULg=,tag:LIfzbV0blHYJcnTzdom1Aw==,type:str]
ansible_user: ENC[AES256_GCM,data:Stm62udSrQ==,iv:uhB2jfnQMiymDBCBcqjtF97Y8iiA4PoeHXVsOEpCBuM=,tag:Zr6jdiIGtruWTDrKR4+2Tw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:c0dqdYnKkK1Qac0=,iv:J6XS0KvOjLSGnsynG7Twt1UjNTC/T76UYQvcmVUbAdE=,tag:ORxO3+8xcb9FJVkUpGJchA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q0kewssezsdnnf42tkgw2nsjl5qqvvquteftg6cxnzj6cuflrujsumrq5p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRFU5ZlJqWFRXZDJ4Z0I4
            eVpEaTkxbHMweE56Y0ZXZTErOGIxeDlUY1NRCllyQWJ3Wmk3UUxDaEZrZjB0TlBh
            WDZLbzZsTFprblAyUU11K2lJZ0dLUTgKLS0tIGJmSDFtd2hQT3B4R1Fpam13MWww
            bnBxRXl1UEVqZG9LUDdNKzMraEJZV2sKe04n9OONG2FRkBGXdqY9GZ2xkc7VoF7F
            4Yj4ECJ7sNycNMBGvvlM5WnFjy75YsOThxJObz7TsG/foDiX1HDmxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-07T05:28:45Z"
    mac: ENC[AES256_GCM,data:MmdEFmH2ej0NvAZKTSkPB2JfJmrLEPed0uAJvKSqrwLR+/wi8L5bNnImMjBSUI/HvQDApdMeClJRTw6DC2HAPF1g3mcw6/KzwL31YUyzXWeVM7T037E2/soHrtuHh6FWNKXkgbcycxcugT5jO4LOg+HYcCD5SVegRO1Zg4Ap4OY=,iv:/ABPxuuGgsFreje/yNDQZM4DM/hnT5wcy+dEzLvi9Ho=,tag:XKq+Ep0kicpDjxjCHdlZqw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
