---
kubernetes:
  children:
    master:
      hosts:
        k3s-master1:
          ansible_host: 192.168.38.120
        k3s-master2:
          ansible_host: 192.168.38.121
        k3s-master3:
          ansible_host: 192.168.38.122
    worker:
      hosts:
        k3s-worker2:
          ansible_host: 192.168.38.123
