apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:+lD5c94mzjmLXdARXcxVfCQbZqFKjJ39UpdBhNxOjNNIEPIZTg==,iv:E7fCAzxL8DgTbg/e7ntBN/5cSgtediLkiSIydWjiTZ4=,tag:Ru4XE5a9kDbjQWlaX39oog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q0kewssezsdnnf42tkgw2nsjl5qqvvquteftg6cxnzj6cuflrujsumrq5p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaR0ZEeUFZWWUyUklRY05z
            SlkzdlZVMmN6a213dTZCWFB4Rk41cTZTbDNNCjhxYWJLcERlQUF1Z2ZQY1VSbFVi
            Sm9yeGp3ZjBDdFdvb2RSWDNoWXRLdHMKLS0tIGtnWHNSQjFPTGM5Z3B0OTA3allE
            UVJrOTd2eEpBSUVzUmFORElnMTl6RTAKiIG3KdEbkYCctpq5HrBpESHURM7YP+uL
            GTum+mvDiygBTSfOj0CkZUm8ZkTJBDT5YTiNYwmNok2eM/14R+5sCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-05T03:08:12Z"
    mac: ENC[AES256_GCM,data:WtBD707bGaZ2OmtsJg2dduHvaXs7FRV1E5oFFMVXYDR5tyY6tYt7wPuLQA0nsvD03dqTPaETdhqU4AiRYPPZpbdgaNbRNzqN8efGx/BkO1hwjPg+iZYmhA2STx84cVfkxRQk8O09k+XRgZoH/IAhPytiDeY7xGmIO71gntEt55U=,iv:+a2HzCEPURs8yARTjJOpZqAp+j/efQMQ/q0YvRcQsng=,tag:GIBCCM/oyIdQBuL9uB/pDQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
