apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:rUwdtYyNKNv9O5Mk6aMwy0xcHzYtpbI=,iv:5l9B57MNzAH6S4HjqFCApeJkz4x+HQXtBoCvYDe9nEc=,tag:Ibs96uAwrbUCoBjJxpE4ng==,type:str]
    api-key: ENC[AES256_GCM,data:SrALf3pNiW+v2ZEBQx9+WxveEcQVjfvpY0/5HECYsznkbMD5cQ==,iv:HH4Z1isCS8RHgHQ6Sd8pZELoG3bJETvJBrHMSxEobv8=,tag:iAu0CkJGb67wX4PVa3IuJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q0kewssezsdnnf42tkgw2nsjl5qqvvquteftg6cxnzj6cuflrujsumrq5p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjM3ZrSXBqZzRLUjVCakIy
            YXBaa3h2YXllZlk4T0xZY2cyMithb01uOTNjCndsckY5OWRRSjJaSUlUZTIyUWkw
            ZlA2eCtjU0p1cGxoZGUvaG5DL3RVbjgKLS0tIEZ1SlUyNU4wUUtJY0ZCdmhXaVZs
            d0NPeG15Ulc5QVN1RnNYaW9JdDkvcjAKK0Y/vb6l85b/d5XRGCuWRnT8dJW6w4Oy
            4/mtoDr1I3xXWiv2gmGcMo2HuHx03Nhn/7FKzy+Cm/GycHwqgrNO1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-05T03:08:12Z"
    mac: ENC[AES256_GCM,data:iaty3/yh9NP122jBg6W1OotDeBrCXJmYFfiPBg8pFOtnPfPh9LVHtcuYRGpam5nbghK+Q/F7btbp0OF86MlNpPQwArpc5dljwJBysCeJyFLNtlg9AyDgv3jSpOr/xopdtilg/iGsSMaT3apfOuVz59fW0MH2DLlPqK4xd0WheSw=,iv:3YWSQB0fbhq5DEOM+QG+hvJriDRbZMNP+z068/M5jXc=,tag:uGTfxo3czc6+qjTBRfElgA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
