apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:WCoEREFQS3w4CnmHAaZxTsavfVXNU3EGoTQ0zXDyu3gM8jKoKHFIrN/4Rea9Xm8e0iThRsXsT/FcFZeA,iv:HM7CkyHDCLDyyXgyhnIfRqHUToUe/eT/8UI6K5KNCis=,tag:dbesjok3g2FSXEtaBGESjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q0kewssezsdnnf42tkgw2nsjl5qqvvquteftg6cxnzj6cuflrujsumrq5p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTzdoa0djM1N5WTVhSGYy
            UmhrbytpL0ZzVC9DdURhcWN2MVpaVTMvQ3ljCnRiSlpBNWNZUXZWOVBNUHdDRDBi
            ZVlkWGVNSjcya0JWNEZkLzVic2UxWGcKLS0tIHZ3RFhSQUZKWkFaWWhLM2poNU1C
            TVIyb1ZEMCtYSVI3bXl4K3RUNDljN2cKLQA3699xbxMFxVZCkxdxgHurAtHuqVFi
            Pql/f4stZzZULxFsLefao9JMzhyIKF2ceXJCFJmFMvueC3l65IXEkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-07T06:17:18Z"
    mac: ENC[AES256_GCM,data:V5DRni234qt4+OscqId6bFh1wLfP1G7O8WQPO2QE/ug1erTgaQre3zbyR2ewvvfu3Dx8ebrvpORfhY6t3ujcbrZoAsrIwwzE2H8AtXaMzcU7X6T2s2ckmUlZKD0CKzvv0Jij3iQ6XmZt09wofUZxnzTUYp3hBxKmmfrAsDsG1dQ=,iv:QgxXCk10ouvEDQVVEwWC+Oy5Fpsci7zFYNCUB9UWbKA=,tag:+yLD4mEv8H1oIMC30JztJg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
