apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:+6swENZjOY4rgYdf+bPGZvsB7H1NXXxfo/Gs3RwapyXvypluqZcZwZU/G1lfW8uJSIjCMkkTpmhkE97j,iv:DOHutV1uumVzKmYdYjSv6P1JCXhRai9nlJFj+L7H7sQ=,tag:rS1buBKzBUoeBT9u12BV/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q0kewssezsdnnf42tkgw2nsjl5qqvvquteftg6cxnzj6cuflrujsumrq5p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WWNLUTk1TWVqVmpNd0Fa
            MVRGMStwaFFLN0I3L0gvbmhUS0JMQXZicDE0CklUcVR3NExOVUNxdS9Id0FNb1ow
            bE1CM0h5dnBiUlVWYmRZN2xScTNUSlEKLS0tIEVmTUxNZzJ6NkpLbEN5QU14QkJx
            c2xiSlhTditIUEdHeldDeEpEN2JCczAKW1gri50rWxP9QtJj3n69IAATbADkNMFL
            AEcMXIaN9YntcwS6g5BKGzMCPxj4qIH3JAmls9ScGvTIaqzSPhxKKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-05T19:38:55Z"
    mac: ENC[AES256_GCM,data:iKPZXwg/cJ6JgFdyOhJ0X4C4PZmXMLjVoCQLoGizJrCe3zOgKfFEAxBl+Uf7q1uZZTA6bovVGJK1vvAmFFmoyj9zbHwy9bfScQrEtBJse5Ay31vb93O4FpIwxmzfANPpHl7wbp3eKSMw04f++k8OKZ/u0aqGja5s6Rumu/gk+pE=,iv:lmQ+IFfWqgyWtdRmSERqGLlwtfVwsVe0CkRVnkv/oa0=,tag:eLP0upB42EFEfA1gm0EXqg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
