apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:JZImlWx6xR0Cu3Lyh7cIdXggiLo2fq3nLx3y9ZnUf39PEhEhWzQ9muqvxb5UJ7tyqs/Dw7szlZJomhc3,iv:7XMBwzgNmXVRGb9kpTTC4f+SbpVuTrxLvTuQI17FGYA=,tag:2Mk4hGfBu8Bag6kdhrOYjQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q0kewssezsdnnf42tkgw2nsjl5qqvvquteftg6cxnzj6cuflrujsumrq5p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoV1NFOEREY0ZMMzNwaTJY
            blA3UmZFTUZZRm0rVEkvVit1cFZNM2pobjJZCjBseUd5Z05NYWpCd0JZYmxCSlVB
            cXpJaUJpbDQ4S2FUdW5yNzhXMURNa2sKLS0tIHJscGY3cW54ckxFMmJKMkc2dmpn
            dkJERm5zZGt5MW1OZ242dDdGZUNud0kKsUBWBiriXKMTh7QrTTL2lsK8/1dww11H
            5KrmIZSkXXZCaZxibDtw01Np9i8mUAaT1lbN/qlK4HsQqwVgDsX4hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-07T05:28:45Z"
    mac: ENC[AES256_GCM,data:Y1ystIIe7Ec9/x2X0R9uHRMtmqA7EqzjAYYvOMV2EoTKlkyBIHuNeP4eRPwtROBxDjuRRhfIFCB6I03E1y1I1UbFQlLEdLkLHi7ph7xPRWyQnQIPHg2msTPatr9Sc8r7pqrDV1qbZyfs1xNxJdHu4o7kKeYN8xazlO1d7XDyzLw=,iv:+SngSEbbthKvnp3rjPZoh8VsxOYlHZdNcKBt1gYItOM=,tag:YifnAnw9UBYStDqx/5staA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
