apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:3/vwCZMD5WusBs9FQhAM1eefbXOhrRCO9NloZ8W61GvY8Dkd,iv:i+dF87P83BnyX1uwAiBex2KZ0PN9bnjtrwjiUshc+Rg=,tag:r3vOBOTffJNqkWulaE18ZA==,type:str]
    credentials.json: ENC[AES256_GCM,data:A0+yeHUDRdzsPrJVbAtH3nV/yr0RDAbdCUu1K7ZCyosk6ZnM1+G5QR0zF1mum4yxCUuCpvKNZWpRlHgszUcxHLxLjIzgOCs/7dG3zwJzrRtrB+r7chJ6Vkn83SZ3WWlGdNeu4swP3Wxp9X6P5KraXEIJJCX4JPHeASZTnNCuqdo1JD8acOt2yZ6TpE+vETI2qNNC5pFckzHzF20hHmHzW0LR2Mha4y1r3d8msnVOUw==,iv:e7QVqBkNZvKQ5eWTLchAqb8jX1vv4sHApGeS25eatSY=,tag:IyfWDaf5pLw+X2xOzy86xg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q0kewssezsdnnf42tkgw2nsjl5qqvvquteftg6cxnzj6cuflrujsumrq5p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bVUzQ25jeWdjbEFtMXdR
            WTBCeG5mNE5LOEZGcWFHa1hsQ3hobmRkWDJJClBTWGZyaE1CQ0MwUzNKeTVtVmc3
            UW1yamEvbVY3bmZhWU5SVnFYTkREV00KLS0tIEdDTFM4MEVuYnRmZlhaL1pTaUhp
            VU05Mk9menRzazltSEw4d1RRY1YxZ0EKuMn0krdVqut7wEgYe6Y1I8Ip6WlybR4O
            +Rr74CDxNycmcvAV0uYZPjNOlC7WHe+M6asHKgLDDuZ+dtTdfo74jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-05T03:08:12Z"
    mac: ENC[AES256_GCM,data:pztEeuJv74B6BrUrMIZ8yj8G3rB3d6Gz5dPpLOTtKeqWVSvqw0t52vb6GI/qB+U2ex+llTd372ZuUs6udOX2Sx9Ra/We7/JLzSX4yKwoaESXqe5gql8SoE9p0iCdcntsuRfUg4zEdrxNqRrJYSt7hAUuf0lglZ7B6gv9eoSmpXE=,iv:9JwF6Pb/TOo+ZjILEn6gpR5AkzUYwh9XhRW1yljrpUA=,tag:VJbUxNx5442eVCtH1RjM/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
