apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:zyqMrGddL3yYB/uTbbLKqsMlnIbRGBTWaZCWfta0bWBkZHJU,iv:lJqV+tv3083vbjGyPnzqOQHOzAMe9QDnR9Z6juNOYZk=,tag:xntzE8ue5SfyBusZxxFacg==,type:str]
    credentials.json: ENC[AES256_GCM,data:UQFdeEeCyXB6dsHuqrhD0E4EE6qpBYxNDdECIZZFBOpFBGmJTIFo3QxZq7kL4jSekEeXEKhrBKrmaIrHbzD1Fv4eKYDuM9pmyGwdOw2jVtrYc/TvOGL2GyopXNwAdct9mWxY7QGUOoeAW47NPhCPElI4Gq7iK1OWWLaZwyMOuBydQz9POsX5NNhM6xjZyjnYNpRaNuM8giWnT8UT4+6NKRNgFlPVuiiJCbX9cjl/cw==,iv:V4FnikCLGHRrfldp6yMmZjzk6iWSe5E3jzuWDi5L2OU=,tag:SQoWUPb0E2bnP8H3j0SURA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q0kewssezsdnnf42tkgw2nsjl5qqvvquteftg6cxnzj6cuflrujsumrq5p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldENoNXVhaW1vWmxkTEYv
            cjRXRjl1M1M1bEVTNmRlTEcrYlpCRTMvQXpnCnJCRU12U1Y3cjlKbkJyWWlkaGEz
            V24yaUl4WjF3V3hhUERHa1Fqb1RCbzAKLS0tIHUwSVZleTFDK29qMHFjVzZRODBH
            clFYWG5mYnB4eWxWYUI0S0JkTlpScGMKHaojKECNqxWbW82X8eO5gET7aXXMlX09
            iKevDRBZxTN98UFiBiRyXla8AhTMr93BqmqICP1I26AaHwLpGZsdaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-07T06:17:18Z"
    mac: ENC[AES256_GCM,data:Px4noMCkAQMWYgKMUqx5CE7j1wCmBVffKojT+C1n1da8b0v4njEeeon0Aq8Sx3wCQaUcZztsEHh7h8Wlvg+Bbxf/UWT8ZhzrbTEgo5LLujK8Q1ChJvQSXMiDmPS42FpYa+mnH99gT1AlEBPJiS4GdT8MQU7+WQ2ToyAoDsPGcRw=,iv:HpazT6rVWTc32PwOEwyOqjQYIFOggbGP4QMPcuZNoWA=,tag:VfvZkNYkGuoHupWbPbU1pA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
